import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import '@/app/globals.css'

import { getServerSession } from 'next-auth'
import { authOptions } from '../api/auth/[...nextauth]/route'
import UserInfo from './components/user-info'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'CKPC 31st Anniversary',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const session = await getServerSession(authOptions);
  return (
    <html lang="zh-Hant-TW" className='w-full h-full'>
      <body className={inter.className}>
        <div className='flex flex-col gap-2 p-8'>
          <UserInfo session={session} />
          {children}
        </div>
      </body>
    </html>
  )
}
